### Importing Library

In [1]:
import numpy as np

### Array attributes

In [8]:
a=np.array([1,2,3]) #1-d / vector

In [9]:
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.shape

(3,)

In [12]:
a.ndim

1

In [13]:
b=np.array([[1,2,3],
           [4,5,6]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
type(b)

numpy.ndarray

In [16]:
b.shape

(2, 3)

In [17]:
b.ndim

2

In [34]:
c=np.array([[[1.0,2,3],
           [4,5,6],
           [7,8,9]]])

In [35]:
c

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [36]:
d=np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
           
           [[10,11,12],
           [13,14,15],
           [16,17,18]]])

In [37]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [39]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [43]:
a.size,b.size,c.size,d.size # determine how many elements are therein an array

(3, 6, 9, 18)

In [44]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes #determine how many bytes consumed by an array

(12, 24, 72, 72)

### Array creation